diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=uearngold@outlook.com
credential.https://git.heroku.com.provider=generic
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/ZigZagExchange/frontend.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.uiRedesign.remote=origin
branch.uiRedesign.merge=refs/heads/uiRedesign
branch.update/some-components.remote=origin
branch.update/some-components.merge=refs/heads/update/some-components
lfs.repositoryformatversion=0
branch.update/fix-issues.remote=origin
branch.update/fix-issues.merge=refs/heads/update/fix-issues
