export { default as PlusIcon } from "./Icons/Plus"
export { default as MinusIcon } from "./Icons/Minus"
export { default as CompareArrowIcon } from "./Icons/CompareArrow"
export { default as EditIcon } from "./Icons/Edit"
export { default as DeleteIcon } from "./Icons/Delete"
export { default as DownIcon } from "./Icons/Down"
export { default as RightIcon } from "./Icons/Right"
export { default as LeftIcon } from "./Icons/Left"
export { default as UpIcon } from "./Icons/Up"
export { default as DiscordIcon } from "./Icons/Discord"
export { default as TelegramIcon } from "./Icons/Telegram"
export { default as GithubIcon } from "./Icons/Github"
export { default as TwitterIcon } from "./Icons/Twitter"
export { default as InfoIcon } from "./Icons/Info"

export { default as Svg } from "./Svg";
