export const initialLayouts = {
    xl: [
        {
            w: 7,
            h: 20,
            x: 0,
            y: 0,
            i: "a",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 7,
            h: 20,
            x: 0,
            y: 0,
            i: "b",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 23,
            h: 20,
            x: 17,
            y: 0,
            i: "c",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 33,
            h: 10,
            x: 7,
            y: 20,
            i: "d",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 10,
            h: 10,
            x: 7,
            y: 0,
            i: "e",
        },
        {
            w: 10,
            h: 10,
            x: 7,
            y: 10,
            i: "f",
        },
        {
            w: 5,
            h: 20,
            x: 7,
            y: 0,
            i: "g",
        },
        {
            w: 5,
            h: 20,
            x: 12,
            y: 0,
            i: "h",
        },
    ],
    lg: [
        {
            w: 9,
            h: 20,
            x: 0,
            y: 0,
            i: "a",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 9,
            h: 20,
            x: 0,
            y: 0,
            i: "b",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 17,
            h: 20,
            x: 23,
            y: 0,
            i: "c",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 31,
            h: 10,
            x: 9,
            y: 40,
            i: "d",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 14,
            h: 10,
            x: 9,
            y: 0,
            i: "e",
        },
        {
            w: 14,
            h: 10,
            x: 9,
            y: 0,
            i: "f",
        },
        {
            w: 7,
            h: 20,
            x: 9,
            y: 0,
            i: "g",
        },
        {
            w: 7,
            h: 20,
            x: 16,
            y: 0,
            i: "h",
        },
    ],
    md: [
        {
            w: 11,
            h: 20,
            x: 0,
            y: 0,
            i: "a",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 11,
            h: 20,
            x: 0,
            y: 0,
            i: "b",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 11,
            h: 20,
            x: 29,
            y: 0,
            i: "c",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 29,
            h: 10,
            x: 11,
            y: 40,
            i: "d",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 18,
            h: 10,
            x: 11,
            y: 0,
            i: "e",
        },
        {
            w: 18,
            h: 10,
            x: 11,
            y: 0,
            i: "f",
        },
        {
            w: 9,
            h: 20,
            x: 11,
            y: 0,
            i: "g",
        },
        {
            w: 9,
            h: 20,
            x: 20,
            y: 0,
            i: "h",
        },
    ],
    xxs: [
        {
            w: 2,
            h: 20,
            x: 0,
            y: 20,
            i: "b",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 1,
            h: 20,
            x: 0,
            y: 20,
            i: "a",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 2,
            h: 20,
            x: 0,
            y: 0,
            i: "c",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 2,
            h: 15,
            x: 0,
            y: 60,
            i: "d",
            moved: false,
            static: false,
            isBounded: true,
        },
        {
            w: 2,
            h: 10,
            x: 0,
            y: 40,
            i: "e",
        },
        {
            w: 2,
            h: 10,
            x: 0,
            y: 20,
            i: "f",
        },
        {
            w: 1,
            h: 20,
            x: 1,
            y: 20,
            i: "g",
        },
        {
            w: 2,
            h: 20,
            x: 0,
            y: 40,
            i: "h",
        },
    ],
};
